apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - tedmcp/namespace.yaml
  # tedmcp app — stable channel
  - tedmcp/main/deployment.yaml
  - tedmcp/main/service.yaml
  - tedmcp/main/certificate.yaml
  - tedmcp/main/ingress.yaml
  - tedmcp/main/update.yaml
